### ISSUE TITLE
Please add option source license

### ISSUE THREAD

**Issue by StephanSalas** [senderista/sliding-window-rate-limiter#1]
Can you please add like an MIT or other license so I can use this? Thanks!

**Comment by senderista** [comment]
OK, I added the MIT license, but I should caution you that I don't think this approach to rate limiting is a particularly good one for production. This was a coding exercise for an interview and I used the sliding-window approach only because that was the required semantics. The problem with a sliding window is that it allows an arbitrarily high request rate, as long as the requests don't exceed the maximum allowed for the window. If I were putting a rate limiter into production I would probably start with a token bucket instead.

PS I didn't get the job (I was told this code was too complex) ;)
